### ISSUE TITLE
Testing Errors

### ISSUE THREAD

**Issue by RUGAlbert** [pieterDekker/blockhain-trading-platform#3]
Hey,

I get the following error message when I test it on truffle:
```
 Contract: PaymentAgreements
    1) "before each" hook for "Should emit a NewPaymentAgreement event when a trade agreement is published"

  Contract: TradeAgreements
    2) "before each" hook for "Should emit a NewTradeAgreement event when a trade agreement is published"

  Contract: Traders
    ✓ should allow for new traders to be created (52ms)
    ✓ should correctly report wether an account belongs to a trader (110ms)
    ✓ should return a traders name (82ms)
    ✓ should not allow for a trader to be created twice (121ms)


  23 passing (13s)
  7 pending
  2 failing

  1) Contract: PaymentAgreements
       "before each" hook for "Should emit a NewPaymentAgreement event when a trade agreement is published":
     Error: Invalid number of parameters for "undefined". Got 4 expected 5!
     at PromiEvent (/usr/lib/node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at /usr/lib/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:223:1
      at Function.new (/usr/lib/node_modules/truffle/build/webpack:/packages/contract/lib/contract/constructorMethods.js:57:1)
      at Context.beforeEach (test/unit/PaymentAgreements.js:32:38)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  2) Contract: TradeAgreements
       "before each" hook for "Should emit a NewTradeAgreement event when a trade agreement is published":
     Error: Invalid number of parameters for "undefined". Got 4 expected 5!
     at PromiEvent (/usr/lib/node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
      at /usr/lib/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:223:1
      at Function.new (/usr/lib/node_modules/truffle/build/webpack:/packages/contract/lib/contract/constructorMethods.js:57:1)
      at Context.beforeEach (test/unit/TradeAgreements.js:32:38)
      at process._tickCallback (internal/process/next_tick.js:68:7)

```
And I was wondering if I forget to change something that this happend.
Also in order to compile it in the first place I had to delete the following function:
```
//ROUND CODE
    function roundIsInSession() {
        return roundInSession;
    }
```
Kind regards,
Albert

**Comment by pieterDekker** [comment]
It seems I was a little early with pushing, needed a few more touches. Will be fixed in #4 .
